# Generated by Django 6.0.5 on 2026-05-11 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта (компании)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект аудита',
                'verbose_name_plural': 'Проекты аудитов',
            },
        ),
        migrations.CreateModel(
            name='HardwareRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фермы (например: 4x RTX 4090)')),
                ('power_watts', models.IntegerField(blank=True, null=True, verbose_name='Энергопотребление (Ватт)')),
                ('hashrate_md5', models.BigIntegerField(verbose_name='Скорость перебора MD5 (H/s)')),
                ('hashrate_sha256', models.BigIntegerField(verbose_name='Скорость перебора SHA-256 (H/s)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оборудование для взлома',
                'verbose_name_plural': 'Оборудование для взлома',
            },
        ),
        migrations.CreateModel(
            name='PasswordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_length', models.IntegerField(verbose_name='Длина пароля')),
                ('entropy_score', models.FloatField(verbose_name='Энтропия (бит)')),
                ('time_to_crack_seconds', models.FloatField(verbose_name='Время взлома (секунды)')),
                ('is_pwned', models.BooleanField(default=False, verbose_name='Найден в утечках (Pwned)')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время проверки')),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.hardwarerig', verbose_name='Оборудование')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='audit.auditproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Журнал проверки',
                'verbose_name_plural': 'Журналы проверок',
            },
        ),
    ]
