# Generated by Django 6.0.5 on 2026-05-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('power_watts', models.IntegerField(blank=True, null=True, verbose_name='Энергопотребление (Ватт)')),
                ('hashrate_md5', models.BigIntegerField(verbose_name='Скорость перебора MD5 (H/s)')),
                ('hashrate_sha256', models.BigIntegerField(verbose_name='Скорость перебора SHA-256 (H/s)')),
            ],
            options={
                'verbose_name': 'Оборудование для взлома',
                'verbose_name_plural': 'Оборудование для взлома',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория цели (например: Соцсети, Банкинг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа целей',
                'verbose_name_plural': 'Группы целей',
            },
        ),
        migrations.CreateModel(
            name='PasswordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_length', models.IntegerField(verbose_name='Длина пароля')),
                ('entropy_score', models.FloatField(verbose_name='Энтропия (бит)')),
                ('time_to_crack_seconds', models.FloatField(verbose_name='Время взлома (секунды)')),
                ('is_pwned', models.BooleanField(default=False, verbose_name='Найден в утечках')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('hardware', models.ManyToManyField(to='audit.hardwarerig', verbose_name='Использованное оборудование')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.targetgroup', verbose_name='Группа цели')),
            ],
            options={
                'verbose_name': 'Журнал проверки',
                'verbose_name_plural': 'Журналы проверок',
            },
        ),
    ]
