# Generated by Django 6.0.5 on 2026-05-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordauditlog',
            options={'verbose_name': 'Запись аудита', 'verbose_name_plural': 'Журнал аудита'},
        ),
        migrations.RemoveField(
            model_name='hardwarerig',
            name='power_watts',
        ),
        migrations.AlterField(
            model_name='hardwarerig',
            name='hashrate_md5',
            field=models.BigIntegerField(verbose_name='Скорость MD5 (H/s)'),
        ),
        migrations.AlterField(
            model_name='hardwarerig',
            name='hashrate_sha256',
            field=models.BigIntegerField(verbose_name='Скорость SHA-256 (H/s)'),
        ),
        migrations.AlterField(
            model_name='hardwarerig',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Модель GPU'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='entropy_score',
            field=models.FloatField(verbose_name='Энтропия (bit)'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='hardware',
            field=models.ManyToManyField(to='audit.hardwarerig', verbose_name='Выбранные GPU'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='is_pwned',
            field=models.BooleanField(default=False, verbose_name='В утечках'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='password_length',
            field=models.IntegerField(verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.targetgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='tested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='passwordauditlog',
            name='time_to_crack_seconds',
            field=models.FloatField(verbose_name='Время взлома'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
    ]
