# Generated by Django 6.0.5 on 2026-05-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerig',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ориентировочная цена (руб)'),
        ),
    ]
