# Generated by Django 6.0.5 on 2026-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_passwordauditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerig',
            name='power_watts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Энергопотребление (Ватт)'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория цели'),
        ),
    ]
